name: Build

on: [pull_request]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build 
      uses: docker/build-push-action@v5
      with:
        cache-to: type=gha,mode=max
        cache-from: type=gha
        push: false
