name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build 
      uses: docker/build-push-action@v5
      with:
        cache-to: type=gha,mode=max
        cache-from: type=gha
        push: false
