name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build 
      uses: docker/build-push-action@v5
      with:
        cache-to: type=gha,mode=max
        cache-from: type=gha
        push: false
        tags: churchroad-web-demo

    - name: Start container and copy www/ directory
      run: |
        docker run -d --name churchroad-web-demo churchroad-web-demo
        docker cp churchroad-web-demo:/root/target/www out/
        docker rm -f churchroad-web-demo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
       
